---
- hosts: kubemaster
  become: yes
  remote_user: root
  roles:
    - role: ansible-role-linux-kubernetes
    - role: ansible_role_helm
  vars_files:
    - vars.yaml

- hosts: kubeworker
  become: yes
  remote_user: root
  roles:
    - role: ansible-role-linux-kubernetes
    - role: ansible_role_helm
  vars_files:
    - vars.yaml
