---

- include_tasks: 
    file: "{{ item }}"
    apply:
      tags: repo
  with_first_found:
    - "setup_repo_{{ ansible_os_family }}.yml"
  tags: repo

- setup:

- include_tasks: 
    file: preflight.yml
    apply:
      tags: preflight
  tags: preflight

- include_tasks: 
    file: install_cri.yml
    apply:
      tags: cri
  tags: cri

- include_tasks: 
    file: install_kubectl.yml
    apply:
      tags: kubectl
  tags: kubectl

- include_tasks: 
    file: init_cluster.yml
    apply:
      tags: kubeinit
  tags: kubeinit

- include_tasks: 
    file: join_cluster.yml
    apply:
      tags: kubejoin
  tags: kubejoin

- include_tasks: 
    file: setup_vip.yml
    apply:
      tags: k8s_vip
  tags: k8s_vip
  when: 
    - setup_vip
    - inventory_hostname in groups['kubemaster']

- include_tasks: 
    file: install_longhorn.yml
    apply:
      tags: install_longhorn
  tags: install_longhorn
  when: install_longhorn

- include_tasks: 
    file: install_nginx_ingress.yml
    apply:
      tags: install_nginx_ingress
  tags: install_nginx_ingress
  when: install_nginx_ingress