---

- name: Install required system packages
  ansible.builtin.dnf: 
    name: 
      - redhat-lsb-core
    state: present
    update_cache: yes 

- shell: lsb_release -is
  register: lsb_release

- name: Add Docker Repository
  ansible.builtin.get_url:
    url:  https://download.docker.com/linux/{{ lsb_release.stdout | lower }}/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- shell: uname -m
  register: uname_m

- name: Add K8s Repository
  ansible.builtin.blockinfile:
    create: yes
    path: /etc/yum.repos.d/kubernetes.repo
    block: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-{{ uname_m.stdout }}
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      exclude=kubelet kubeadm kubectl